### ISSUE TITLE
can't pick up any item/fish/turtle in water.

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Framework#573]
using net and get fishes is fine, but can't take dead turtle and fishes in water

**Comment by Jawshy** [comment]
Do you receive any error messages at all, or just nothing simply happen when trying to pick up these animals?

**Comment by Jawshy** [comment]
The following error message is written to the client/local.rpt log file when a player presses the interaction key (Default: Windows Key) when trying to catch fish: 

```
15:40:15 Error in expression <g,3]);
if(!(isNil "_fish")) then {
if ((typeOf _fish) == "Turtle_F" && !alive _f>
15:40:15   Error position: <typeOf _fish) == "Turtle_F" && !alive _f>
15:40:15   Error typeof: Type Array, expected Object
15:40:15 File mpmissions\__CUR_MP.Altis\core\functions\fn_actionKeyHandler.sqf, line 32
```

This error will not occur when interacting with a vehicle or house.

**Comment by tkcjesse** [comment]
Lol yeah... whoever changed the actionKeyHandler didn't use correct syntax.

**Comment by tkcjesse** [comment]
https://github.com/ArmaLife/Altis/commit/a53214ff401ec166bda9d4adb4934729acab2a60

**Comment by Liam0** [comment]
Yeah i got a fix ready for it just adding it to my fix pull as soon as i've done a bit of testing :P

**Comment by Liam0** [comment]
@HyunsukBaek https://github.com/ArmaLife/Altis/commit/d00b4a764e9ca2444def793e0a32c0a495010641 should fix it for you.

**Comment by HyunsukBaek** [comment]
@Liam0  thanks for your kindness, i love it

**Comment by Jawshy** [comment]
Still cannot gather fish. Nothing happens on interaction key press. No errors in RPT.

**Comment by BoGuu** [comment]
@Jawshy 
Use a boat and the fishing net addAction to catch fish normally. You don't swim after fish to try and catch them in the ocean, so shoot -> loot.

**Comment by tkcjesse** [comment]
wait wtf. So you can't just catch live fish anymore?

**Comment by BoGuu** [comment]
Not an issue, catching dead fish is the way it was made to be (use nets!).
